/* gramaticameme.java */
/* Generated By:JavaCC: Do not edit this line. gramaticameme.java */
package pacotememe;

import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.util.ArrayList;
import java.util.List;
import java.util.Set;
import java.util.HashSet;

public class gramaticameme implements gramaticamemeConstants {
  public static List<String> listaErros = new ArrayList<String>();
  public static List<Integer> listaLinhasErros = new ArrayList<Integer>();

  public static void registrarErro(ParseException e) {
      Token proximo = e.currentToken.next;
      String msg = "";
      if (proximo.kind == INVALID) {
          msg = "Erro L\u00e9xico na Linha " + proximo.beginLine + ", Coluna " + proximo.beginColumn + ": caractere inv\u00e1lido '" + proximo.image + "'";
      } else {
          msg = "Erro Sint\u00e1tico na Linha " + proximo.beginLine + ", Coluna " + proximo.beginColumn + ": Encontrado '" + proximo.image + "'. Esperava-se: ";
          Set<String> esperados = new HashSet<String>();
          if (e.expectedTokenSequences != null) {
              for (int i = 0; i < e.expectedTokenSequences.length; i++) {
                  for (int j = 0; j < e.expectedTokenSequences[i].length; j++) {
                      esperados.add(e.tokenImage[e.expectedTokenSequences[i][j]]);
                  }
              }
          }
          msg += String.join(", ", esperados);
      }
      listaErros.add(msg);
      listaLinhasErros.add(proximo.beginLine);
  }

  public static void recuperarErro() {
      Token t;
      while (true) {
          t = getToken(1);
          if (t.kind == EOF) {
              break;
          }
          if (t.kind == PONTO_VIRGULA) {
              getNextToken(); // consome ponto e vírgula
              break;
          }
          if (t.kind == FECHA_CHAVES) {
              // não consome fecha chaves para que o escopo externo trate
              break;
          }
          getNextToken(); // consome outros tokens
      }
  }

  public static void main(String args [])
  {
    if (args.length == 0) {
        // Modo GUI
        javax.swing.SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                new CompilerGUI().setVisible(true);
            }
        });
    } else {
        // Modo CLI (Compatibilidade original)
        gramaticameme parser = new gramaticameme(System.in);
        System.out.println("======================================");
        System.out.println("Bem-vindo ao compilador CompilaMeme");
        System.out.println("Digite o seu c\u00f3digo abaixo. Para encerrar e compilar no terminal,");
        System.out.println("pressione CTRL+Z seguido de Enter");
        System.out.println("======================================\n");

        try
        {
          gramaticameme.Programa();
          if (listaErros.isEmpty()) {
              System.out.println("\n\u2705 Top! C\u00f3digo compilado sem nenhum erro sint\u00e1tico ou l\u00e9xico.");
          } else {
              System.out.println("\n\u274c Vixe, deu red! Erros encontrados durante a compila\u00e7\u00e3o:");
              for (String err : listaErros) {
                  System.out.println("-> " + err);
              }
          }
        }
        catch (ParseException e)
        {
          System.out.println("\n\u274c Vixe, deu red! Erro Sint\u00e1tico encontrado:");
          Token t = e.currentToken;
          Token proximo = t.next;

          System.out.println("-> O erro estourou na linha " + proximo.beginLine + ", coluna " + proximo.beginColumn + ".");
          System.out.println("-> O token que quebrou tudo foi: '" + proximo.image + "'");

          if (t.beginLine < proximo.beginLine) {
              System.out.println("-> DICA: O erro pode estar na linha anterior (" + t.beginLine + ")! Ser\u00e1 que voc\u00ea n\u00e3o esqueceu um ponto e v\u00edrgula ';' ou algo do tipo l\u00e1?");
          }

          System.out.print("-> Mas na true, o compilador tava esperando receber: ");
          for (int i = 0; i < e.expectedTokenSequences.length; i++) {
            for (int j = 0; j < e.expectedTokenSequences[i].length; j++) {
              System.out.print(e.tokenImage[e.expectedTokenSequences[i][j]] + " ");
            }
          }
          System.out.println("\n\nDa seus pulos a\u00ed e tenta de novo!");
        }
        catch (TokenMgrError e)
        {
          System.out.println("\n\ud83d\udeab Erro L\u00e9xico, bicho!");
          String msg = e.getMessage();
          try {
              Pattern p = Pattern.compile("line (\\d+), column (\\d+).*?\\((\\d+)\\)");
              Matcher m = p.matcher(msg);
              if (m.find()) {
                  String linha = m.group(1);
                  String coluna = m.group(2);
                  int ascii = Integer.parseInt(m.group(3));
                  char caractereConvertido = (char) ascii;

                  System.out.println("-> O bagulho travou na Linha " + linha + ", Coluna " + coluna + ".");
                  System.out.println("-> O caractere intruso \u00e9 esse aqui: [" + caractereConvertido + "] (C\u00f3digo ASCII: " + ascii + ")");
              } else {
                  System.out.println("Voc\u00ea digitou um caractere que n\u00e3o existe nos memes.");
                  System.out.println("Detalhe original: " + msg);
              }
          } catch (Exception ex) {
              System.out.println("Voc\u00ea digitou um caractere que n\u00e3o existe nos memes.");
              System.out.println("Detalhe t\u00e9cnico: " + msg);
          }
          System.out.println("\nLimpa essa sujeira a\u00ed e tenta de novo!");
        }
    }
  }

/* ========================================================= */
/* INÍCIO DA GRAMÁTICA (ANÁLISE SINTÁTICA)                   */
/* ========================================================= */
  static final public 
ASTNode Programa() throws ParseException {ASTNode node = new ASTNode("Programa");
  ASTNode cmd;
  ASTNode rest = null;
    try {
      label_1:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case T_BRABO:
        case T_REAL:
        case T_FOFOCA:
        case T_SE:
        case T_ENQUANTO:
        case T_PARA:
        case T_F:
        case ID:{
          ;
          break;
          }
        default:
          jj_la1[0] = jj_gen;
          break label_1;
        }
        cmd = Comando();
if (cmd != null) node.addChild(cmd);
      }
      jj_consume_token(0);
{if ("" != null) return node;}
    } catch (ParseException e) {
registrarErro(e);
    if (getToken(1).kind != EOF) {
        getNextToken();
    }
    rest = Programa();
    if (rest != null) {
        for (ASTNode child : rest.getChildren()) {
            node.addChild(child);
        }
    }
    {if ("" != null) return node;}
    }
    throw new Error("Missing return statement in function");
}

  static final public ASTNode Comando() throws ParseException {ASTNode node = null;
    try {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case T_BRABO:
      case T_REAL:
      case T_FOFOCA:{
        node = Declaracao();
        break;
        }
      case T_F:
      case ID:{
        node = AtribuicaoOuImpressao();
        break;
        }
      case T_SE:{
        node = Condicional();
        break;
        }
      case T_ENQUANTO:{
        node = LacoEnquanto();
        break;
        }
      case T_PARA:{
        node = LacoPara();
        break;
        }
      default:
        jj_la1[1] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
{if ("" != null) return node;}
    } catch (ParseException e) {
registrarErro(e);
    recuperarErro();
    {if ("" != null) return new ASTNode("Erro Sint\u00e1tico", e.currentToken.next.image, e.currentToken.next.beginLine, e.currentToken.next.beginColumn);}
    }
    throw new Error("Missing return statement in function");
}

  static final public ASTNode Declaracao() throws ParseException {Token tType = null;
  Token tId = null;
  ASTNode node = new ASTNode("Declara\u00e7\u00e3o");
  ASTNode expr = null;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case T_BRABO:{
      tType = jj_consume_token(T_BRABO);
      break;
      }
    case T_REAL:{
      tType = jj_consume_token(T_REAL);
      break;
      }
    case T_FOFOCA:{
      tType = jj_consume_token(T_FOFOCA);
      break;
      }
    default:
      jj_la1[2] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
node.addChild(new ASTNode("Tipo", tType.image, tType.beginLine, tType.beginColumn));
    tId = jj_consume_token(ID);
ASTNode decl = new ASTNode("Vari\u00e1vel", tId.image, tId.beginLine, tId.beginColumn);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case ATRIB:{
      jj_consume_token(ATRIB);
      expr = Expressao();
decl.addChild(expr);
      break;
      }
    default:
      jj_la1[3] = jj_gen;
      ;
    }
node.addChild(decl);
    label_2:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case VIRGULA:{
        ;
        break;
        }
      default:
        jj_la1[4] = jj_gen;
        break label_2;
      }
      jj_consume_token(VIRGULA);
      tId = jj_consume_token(ID);
decl = new ASTNode("Vari\u00e1vel", tId.image, tId.beginLine, tId.beginColumn);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case ATRIB:{
        jj_consume_token(ATRIB);
        expr = Expressao();
decl.addChild(expr);
        break;
        }
      default:
        jj_la1[5] = jj_gen;
        ;
      }
node.addChild(decl);
    }
    jj_consume_token(PONTO_VIRGULA);
{if ("" != null) return node;}
    throw new Error("Missing return statement in function");
}

  static final public ASTNode AtribuicaoOuImpressao() throws ParseException {Token tId = null;
  ASTNode node = null;
  ASTNode expr = null;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case ID:{
      tId = jj_consume_token(ID);
      jj_consume_token(ATRIB);
      expr = Expressao();
      jj_consume_token(PONTO_VIRGULA);
node = new ASTNode("Atribui\u00e7\u00e3o", tId.image, tId.beginLine, tId.beginColumn);
      node.addChild(expr);
      break;
      }
    case T_F:{
      jj_consume_token(T_F);
      jj_consume_token(ABRE_PAR);
      expr = Expressao();
      jj_consume_token(FECHA_PAR);
      jj_consume_token(PONTO_VIRGULA);
node = new ASTNode("Impress\u00e3o (F)");
      node.addChild(expr);
      break;
      }
    default:
      jj_la1[6] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
{if ("" != null) return node;}
    throw new Error("Missing return statement in function");
}

  static final public ASTNode Condicional() throws ParseException {ASTNode node = new ASTNode("Condicional (tem_certeza?)");
  ASTNode expr = null;
  ASTNode cmd = null;
  ASTNode blockTrue = new ASTNode("Ent\u00e3o");
  ASTNode blockFalse = new ASTNode("Sen\u00e3o");
    jj_consume_token(T_SE);
    jj_consume_token(ABRE_PAR);
    expr = Expressao();
    jj_consume_token(FECHA_PAR);
ASTNode condNode = new ASTNode("Condi\u00e7\u00e3o");
    condNode.addChild(expr);
    node.addChild(condNode);
    jj_consume_token(ABRE_CHAVES);
    label_3:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case T_BRABO:
      case T_REAL:
      case T_FOFOCA:
      case T_SE:
      case T_ENQUANTO:
      case T_PARA:
      case T_F:
      case ID:{
        ;
        break;
        }
      default:
        jj_la1[7] = jj_gen;
        break label_3;
      }
      cmd = Comando();
if (cmd != null) blockTrue.addChild(cmd);
    }
    jj_consume_token(FECHA_CHAVES);
node.addChild(blockTrue);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case T_SENAO:{
      jj_consume_token(T_SENAO);
      jj_consume_token(ABRE_CHAVES);
      label_4:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case T_BRABO:
        case T_REAL:
        case T_FOFOCA:
        case T_SE:
        case T_ENQUANTO:
        case T_PARA:
        case T_F:
        case ID:{
          ;
          break;
          }
        default:
          jj_la1[8] = jj_gen;
          break label_4;
        }
        cmd = Comando();
if (cmd != null) blockFalse.addChild(cmd);
      }
      jj_consume_token(FECHA_CHAVES);
node.addChild(blockFalse);
      break;
      }
    default:
      jj_la1[9] = jj_gen;
      ;
    }
{if ("" != null) return node;}
    throw new Error("Missing return statement in function");
}

  static final public ASTNode LacoEnquanto() throws ParseException {ASTNode node = new ASTNode("La\u00e7o Enquanto (segue_o_baile)");
  ASTNode expr = null;
  ASTNode cmd = null;
  ASTNode body = new ASTNode("Corpo");
    jj_consume_token(T_ENQUANTO);
    jj_consume_token(ABRE_PAR);
    expr = Expressao();
    jj_consume_token(FECHA_PAR);
ASTNode cond = new ASTNode("Condi\u00e7\u00e3o");
    cond.addChild(expr);
    node.addChild(cond);
    jj_consume_token(ABRE_CHAVES);
    label_5:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case T_BRABO:
      case T_REAL:
      case T_FOFOCA:
      case T_SE:
      case T_ENQUANTO:
      case T_PARA:
      case T_F:
      case ID:{
        ;
        break;
        }
      default:
        jj_la1[10] = jj_gen;
        break label_5;
      }
      cmd = Comando();
if (cmd != null) body.addChild(cmd);
    }
    jj_consume_token(FECHA_CHAVES);
node.addChild(body);
    {if ("" != null) return node;}
    throw new Error("Missing return statement in function");
}

  static final public ASTNode LacoPara() throws ParseException {ASTNode node = new ASTNode("La\u00e7o Para (ja_acabou_jessica)");
  Token tType = null;
  Token tIdInit = null;
  Token tIdStep = null;
  ASTNode exprInit = null;
  ASTNode exprCond = null;
  ASTNode exprStep = null;
  ASTNode cmd = null;
  ASTNode body = new ASTNode("Corpo");
    jj_consume_token(T_PARA);
    jj_consume_token(ABRE_PAR);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case T_BRABO:{
      tType = jj_consume_token(T_BRABO);
      break;
      }
    case T_REAL:{
      tType = jj_consume_token(T_REAL);
      break;
      }
    case T_FOFOCA:{
      tType = jj_consume_token(T_FOFOCA);
      break;
      }
    default:
      jj_la1[11] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    tIdInit = jj_consume_token(ID);
    jj_consume_token(ATRIB);
    exprInit = Expressao();
    jj_consume_token(PONTO_VIRGULA);
ASTNode initNode = new ASTNode("Inicializa\u00e7\u00e3o");
      ASTNode varNode = new ASTNode("Vari\u00e1vel", tIdInit.image, tIdInit.beginLine, tIdInit.beginColumn);
      varNode.addChild(new ASTNode("Tipo", tType.image));
      varNode.addChild(exprInit);
      initNode.addChild(varNode);
      node.addChild(initNode);
    exprCond = Expressao();
    jj_consume_token(PONTO_VIRGULA);
ASTNode condNode = new ASTNode("Condi\u00e7\u00e3o");
      condNode.addChild(exprCond);
      node.addChild(condNode);
    tIdStep = jj_consume_token(ID);
    jj_consume_token(ATRIB);
    exprStep = Expressao();
ASTNode stepNode = new ASTNode("Passo");
      ASTNode varStep = new ASTNode("Vari\u00e1vel", tIdStep.image, tIdStep.beginLine, tIdStep.beginColumn);
      varStep.addChild(exprStep);
      stepNode.addChild(varStep);
      node.addChild(stepNode);
    jj_consume_token(FECHA_PAR);
    jj_consume_token(ABRE_CHAVES);
    label_6:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case T_BRABO:
      case T_REAL:
      case T_FOFOCA:
      case T_SE:
      case T_ENQUANTO:
      case T_PARA:
      case T_F:
      case ID:{
        ;
        break;
        }
      default:
        jj_la1[12] = jj_gen;
        break label_6;
      }
      cmd = Comando();
if (cmd != null) body.addChild(cmd);
    }
    jj_consume_token(FECHA_CHAVES);
node.addChild(body);
    {if ("" != null) return node;}
    throw new Error("Missing return statement in function");
}

  static final public ASTNode Expressao() throws ParseException {ASTNode node = null;
    node = ExpressaoRelacional();
{if ("" != null) return node;}
    throw new Error("Missing return statement in function");
}

  static final public ASTNode ExpressaoRelacional() throws ParseException {ASTNode left = null;
  ASTNode right = null;
  Token op = null;
    left = ExpressaoAritmetica();
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case IGUAL:
    case DIFERENTE:
    case MAIOR:
    case MENOR:
    case MAIOR_IGUAL:
    case MENOR_IGUAL:{
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case IGUAL:{
        op = jj_consume_token(IGUAL);
        break;
        }
      case DIFERENTE:{
        op = jj_consume_token(DIFERENTE);
        break;
        }
      case MAIOR:{
        op = jj_consume_token(MAIOR);
        break;
        }
      case MENOR:{
        op = jj_consume_token(MENOR);
        break;
        }
      case MAIOR_IGUAL:{
        op = jj_consume_token(MAIOR_IGUAL);
        break;
        }
      case MENOR_IGUAL:{
        op = jj_consume_token(MENOR_IGUAL);
        break;
        }
      default:
        jj_la1[13] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      right = ExpressaoAritmetica();
ASTNode temp = new ASTNode("OpRelacional", op.image, op.beginLine, op.beginColumn);
      temp.addChild(left);
      temp.addChild(right);
      left = temp;
      break;
      }
    default:
      jj_la1[14] = jj_gen;
      ;
    }
{if ("" != null) return left;}
    throw new Error("Missing return statement in function");
}

  static final public ASTNode ExpressaoAritmetica() throws ParseException {ASTNode left = null;
  ASTNode right = null;
  Token op = null;
    left = Termo();
    label_7:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case PLUS:
      case MINUS:{
        ;
        break;
        }
      default:
        jj_la1[15] = jj_gen;
        break label_7;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case PLUS:{
        op = jj_consume_token(PLUS);
        break;
        }
      case MINUS:{
        op = jj_consume_token(MINUS);
        break;
        }
      default:
        jj_la1[16] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      right = Termo();
ASTNode temp = new ASTNode("OpAritm\u00e9tico", op.image, op.beginLine, op.beginColumn);
      temp.addChild(left);
      temp.addChild(right);
      left = temp;
    }
{if ("" != null) return left;}
    throw new Error("Missing return statement in function");
}

  static final public ASTNode Termo() throws ParseException {ASTNode left = null;
  ASTNode right = null;
  Token op = null;
    left = Fator();
    label_8:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case MULTIPLY:
      case DIVIDE:{
        ;
        break;
        }
      default:
        jj_la1[17] = jj_gen;
        break label_8;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case MULTIPLY:{
        op = jj_consume_token(MULTIPLY);
        break;
        }
      case DIVIDE:{
        op = jj_consume_token(DIVIDE);
        break;
        }
      default:
        jj_la1[18] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      right = Fator();
ASTNode temp = new ASTNode("OpMultiplicativo", op.image, op.beginLine, op.beginColumn);
      temp.addChild(left);
      temp.addChild(right);
      left = temp;
    }
{if ("" != null) return left;}
    throw new Error("Missing return statement in function");
}

  static final public ASTNode Fator() throws ParseException {Token t = null;
  ASTNode node = null;
  ASTNode expr = null;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case NUMERO:{
      t = jj_consume_token(NUMERO);
node = new ASTNode("N\u00famero Inteiro", t.image, t.beginLine, t.beginColumn);
      break;
      }
    case NUMERO_FLOAT:{
      t = jj_consume_token(NUMERO_FLOAT);
node = new ASTNode("N\u00famero Decimal", t.image, t.beginLine, t.beginColumn);
      break;
      }
    case STRING:{
      t = jj_consume_token(STRING);
node = new ASTNode("Texto", t.image, t.beginLine, t.beginColumn);
      break;
      }
    case T_TOP:{
      t = jj_consume_token(T_TOP);
node = new ASTNode("Booleano", t.image, t.beginLine, t.beginColumn);
      break;
      }
    case T_TROLL:{
      t = jj_consume_token(T_TROLL);
node = new ASTNode("Booleano", t.image, t.beginLine, t.beginColumn);
      break;
      }
    case ID:{
      t = jj_consume_token(ID);
node = new ASTNode("Identificador", t.image, t.beginLine, t.beginColumn);
      break;
      }
    case ABRE_PAR:{
      jj_consume_token(ABRE_PAR);
      expr = Expressao();
      jj_consume_token(FECHA_PAR);
node = expr;
      break;
      }
    default:
      jj_la1[19] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
{if ("" != null) return node;}
    throw new Error("Missing return statement in function");
}

  static private boolean jj_initialized_once = false;
  /** Generated Token Manager. */
  static public gramaticamemeTokenManager token_source;
  static SimpleCharStream jj_input_stream;
  /** Current token. */
  static public Token token;
  /** Next token. */
  static public Token jj_nt;
  static private int jj_ntk;
  static private int jj_gen;
  static final private int[] jj_la1 = new int[20];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
	   jj_la1_init_0();
	   jj_la1_init_1();
	}
	private static void jj_la1_init_0() {
	   jj_la1_0 = new int[] {0x4de0,0x4de0,0xe0,0x80000,0x8000000,0x80000,0x4000,0x4de0,0x4de0,0x200,0x4de0,0xe0,0x4de0,0x3f00000,0x3f00000,0x18000,0x18000,0x60000,0x60000,0x10003000,};
	}
	private static void jj_la1_init_1() {
	   jj_la1_1 = new int[] {0x1,0x1,0x0,0x0,0x0,0x0,0x1,0x1,0x1,0x0,0x1,0x0,0x1,0x0,0x0,0x0,0x0,0x0,0x0,0xf,};
	}

  /** Constructor with InputStream. */
  public gramaticameme(java.io.InputStream stream) {
	  this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public gramaticameme(java.io.InputStream stream, String encoding) {
	 if (jj_initialized_once) {
	   System.out.println("ERROR: Second call to constructor of static parser.  ");
	   System.out.println("	   You must either use ReInit() or set the JavaCC option STATIC to false");
	   System.out.println("	   during parser generation.");
	   throw new Error();
	 }
	 jj_initialized_once = true;
	 try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source = new gramaticamemeTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 20; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream) {
	  ReInit(stream, null);
  }
  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 20; i++) jj_la1[i] = -1;
  }

  /** Constructor. */
  public gramaticameme(java.io.Reader stream) {
	 if (jj_initialized_once) {
	   System.out.println("ERROR: Second call to constructor of static parser. ");
	   System.out.println("	   You must either use ReInit() or set the JavaCC option STATIC to false");
	   System.out.println("	   during parser generation.");
	   throw new Error();
	 }
	 jj_initialized_once = true;
	 jj_input_stream = new SimpleCharStream(stream, 1, 1);
	 token_source = new gramaticamemeTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 20; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  static public void ReInit(java.io.Reader stream) {
	if (jj_input_stream == null) {
	   jj_input_stream = new SimpleCharStream(stream, 1, 1);
	} else {
	   jj_input_stream.ReInit(stream, 1, 1);
	}
	if (token_source == null) {
 token_source = new gramaticamemeTokenManager(jj_input_stream);
	}

	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 20; i++) jj_la1[i] = -1;
  }

  /** Constructor with generated Token Manager. */
  public gramaticameme(gramaticamemeTokenManager tm) {
	 if (jj_initialized_once) {
	   System.out.println("ERROR: Second call to constructor of static parser. ");
	   System.out.println("	   You must either use ReInit() or set the JavaCC option STATIC to false");
	   System.out.println("	   during parser generation.");
	   throw new Error();
	 }
	 jj_initialized_once = true;
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 20; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(gramaticamemeTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 20; i++) jj_la1[i] = -1;
  }

  static private Token jj_consume_token(int kind) throws ParseException {
	 Token oldToken;
	 if ((oldToken = token).next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 if (token.kind == kind) {
	   jj_gen++;
	   return token;
	 }
	 token = oldToken;
	 jj_kind = kind;
	 throw generateParseException();
  }


/** Get the next Token. */
  static final public Token getNextToken() {
	 if (token.next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 jj_gen++;
	 return token;
  }

/** Get the specific Token. */
  static final public Token getToken(int index) {
	 Token t = token;
	 for (int i = 0; i < index; i++) {
	   if (t.next != null) t = t.next;
	   else t = t.next = token_source.getNextToken();
	 }
	 return t;
  }

  static private int jj_ntk_f() {
	 if ((jj_nt=token.next) == null)
	   return (jj_ntk = (token.next=token_source.getNextToken()).kind);
	 else
	   return (jj_ntk = jj_nt.kind);
  }

  static private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  static private int[] jj_expentry;
  static private int jj_kind = -1;

  /** Generate ParseException. */
  static public ParseException generateParseException() {
	 jj_expentries.clear();
	 boolean[] la1tokens = new boolean[37];
	 if (jj_kind >= 0) {
	   la1tokens[jj_kind] = true;
	   jj_kind = -1;
	 }
	 for (int i = 0; i < 20; i++) {
	   if (jj_la1[i] == jj_gen) {
		 for (int j = 0; j < 32; j++) {
		   if ((jj_la1_0[i] & (1<<j)) != 0) {
			 la1tokens[j] = true;
		   }
		   if ((jj_la1_1[i] & (1<<j)) != 0) {
			 la1tokens[32+j] = true;
		   }
		 }
	   }
	 }
	 for (int i = 0; i < 37; i++) {
	   if (la1tokens[i]) {
		 jj_expentry = new int[1];
		 jj_expentry[0] = i;
		 jj_expentries.add(jj_expentry);
	   }
	 }
	 int[][] exptokseq = new int[jj_expentries.size()][];
	 for (int i = 0; i < jj_expentries.size(); i++) {
	   exptokseq[i] = jj_expentries.get(i);
	 }
	 return new ParseException(token, exptokseq, tokenImage);
  }

  static private boolean trace_enabled;

/** Trace enabled. */
  static final public boolean trace_enabled() {
	 return trace_enabled;
  }

  /** Enable tracing. */
  static final public void enable_tracing() {
  }

  /** Disable tracing. */
  static final public void disable_tracing() {
  }

}
