/* Generated By:JavaCC: Do not edit this line. gramaticamemeConstants.java */
package pacotememe;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface gramaticamemeConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int T_BRABO = 5;
  /** RegularExpression Id. */
  int T_REAL = 6;
  /** RegularExpression Id. */
  int T_FOFOCA = 7;
  /** RegularExpression Id. */
  int T_SE = 8;
  /** RegularExpression Id. */
  int T_SENAO = 9;
  /** RegularExpression Id. */
  int T_ENQUANTO = 10;
  /** RegularExpression Id. */
  int T_PARA = 11;
  /** RegularExpression Id. */
  int T_TOP = 12;
  /** RegularExpression Id. */
  int T_TROLL = 13;
  /** RegularExpression Id. */
  int T_F = 14;
  /** RegularExpression Id. */
  int PLUS = 15;
  /** RegularExpression Id. */
  int MINUS = 16;
  /** RegularExpression Id. */
  int MULTIPLY = 17;
  /** RegularExpression Id. */
  int DIVIDE = 18;
  /** RegularExpression Id. */
  int ATRIB = 19;
  /** RegularExpression Id. */
  int IGUAL = 20;
  /** RegularExpression Id. */
  int DIFERENTE = 21;
  /** RegularExpression Id. */
  int MAIOR = 22;
  /** RegularExpression Id. */
  int MENOR = 23;
  /** RegularExpression Id. */
  int MAIOR_IGUAL = 24;
  /** RegularExpression Id. */
  int MENOR_IGUAL = 25;
  /** RegularExpression Id. */
  int PONTO_VIRGULA = 26;
  /** RegularExpression Id. */
  int VIRGULA = 27;
  /** RegularExpression Id. */
  int ABRE_PAR = 28;
  /** RegularExpression Id. */
  int FECHA_PAR = 29;
  /** RegularExpression Id. */
  int ABRE_CHAVES = 30;
  /** RegularExpression Id. */
  int FECHA_CHAVES = 31;
  /** RegularExpression Id. */
  int ID = 32;
  /** RegularExpression Id. */
  int NUMERO = 33;
  /** RegularExpression Id. */
  int NUMERO_FLOAT = 34;
  /** RegularExpression Id. */
  int STRING = 35;
  /** RegularExpression Id. */
  int INVALID = 36;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"brabo\"",
    "\"realoficial\"",
    "\"fofoca\"",
    "\"tem_certeza?\"",
    "\"senao\"",
    "\"segue_o_baile\"",
    "\"ja_acabou_jessica\"",
    "\"top\"",
    "\"troll\"",
    "\"F\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"=\"",
    "\"==\"",
    "\"!=\"",
    "\">\"",
    "\"<\"",
    "\">=\"",
    "\"<=\"",
    "\";\"",
    "\",\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "<ID>",
    "<NUMERO>",
    "<NUMERO_FLOAT>",
    "<STRING>",
    "<INVALID>",
  };

}
